import type { PropertyRecord } from "@/types";

/**
 * DEMONSTRATION PROPERTY DATA — REPLACE BEFORE LAUNCH.
 *
 * These records exist so the map, filters and listing can be built and reviewed
 * before Supabase is connected. Every entry is fictional:
 *
 * - The names describe plan types, not homes that exist.
 * - No street addresses are stored, and no price figures are invented.
 * - Coordinates are general points inside the three confirmed suburbs, chosen
 *   near arterial roads and undeveloped land so that no pin lands on a real
 *   private residence. They must be replaced with surveyed positions, and each
 *   record's `locationPrecision` reviewed, before this data goes public.
 *
 * `locationPrecision` is enforced by `lib/properties/privacy.ts`, not here: the
 * repository reduces or removes coordinates on the way out, so a mistake in this
 * file cannot leak an exact position for a home that should not have one.
 *
 * Only the three confirmed build areas appear: Mickleham, Craigieburn and
 * Donnybrook. Adding a suburb here adds it to the filters automatically.
 */
export const propertyRecords: readonly PropertyRecord[] = [
  {
    id: "concept-single-storey",
    slug: "single-storey-concept",
    name: "Single storey concept",
    summary:
      "Single level, north-facing living, courtyard to the rear boundary.",
    suburb: "Mickleham",
    state: "VIC",
    postcode: "3064",
    status: "move-in-ready",
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    landSize: 448,
    houseSize: 212,
    placeholderVariant: "single-storey",
    priceDisplay: "Price on application",
    locationPrecision: "exact",
    latitude: -37.5312,
    longitude: 144.8861,
    isFeatured: true,
  },
  {
    id: "concept-double-storey",
    slug: "two-storey-concept",
    name: "Two storey concept",
    summary:
      "Two storey, upper level retreat, double garage under the main roofline.",
    suburb: "Craigieburn",
    state: "VIC",
    postcode: "3064",
    status: "under-construction",
    bedrooms: 4,
    bathrooms: 3,
    carSpaces: 2,
    landSize: 512,
    houseSize: 268,
    placeholderVariant: "double-storey",
    completionLabel: "Completion window to be confirmed",
    priceDisplay: "Price on application",
    locationPrecision: "exact",
    latitude: -37.5974,
    longitude: 144.9412,
    isFeatured: true,
  },
  {
    id: "concept-townhouse",
    slug: "townhouse-concept",
    name: "Townhouse concept",
    summary: "Compact footprint, shared party wall, private upper terrace.",
    suburb: "Donnybrook",
    state: "VIC",
    postcode: "3064",
    status: "completed",
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 1,
    landSize: 262,
    houseSize: 168,
    placeholderVariant: "townhouse",
    locationPrecision: "approximate",
    latitude: -37.5071,
    longitude: 144.9536,
    isFeatured: true,
  },
  {
    id: "concept-wide-frontage",
    slug: "wide-frontage-concept",
    name: "Wide frontage concept",
    summary:
      "Single level across a wide lot, separate living and dining, double garage.",
    suburb: "Mickleham",
    state: "VIC",
    postcode: "3064",
    status: "move-in-ready",
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    landSize: 512,
    houseSize: 231,
    placeholderVariant: "single-storey",
    priceDisplay: "Price on application",
    locationPrecision: "exact",
    latitude: -37.5389,
    longitude: 144.8924,
    isFeatured: false,
  },
  {
    id: "concept-courtyard",
    slug: "courtyard-concept",
    name: "Courtyard concept",
    summary:
      "Three bedrooms wrapped around a sheltered courtyard, single garage.",
    suburb: "Craigieburn",
    state: "VIC",
    postcode: "3064",
    status: "move-in-ready",
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 1,
    landSize: 336,
    houseSize: 164,
    placeholderVariant: "townhouse",
    priceDisplay: "Price on application",
    locationPrecision: "exact",
    latitude: -37.6042,
    longitude: 144.9331,
    isFeatured: false,
  },
  {
    id: "concept-corner-block",
    slug: "corner-block-concept",
    name: "Corner block concept",
    summary:
      "Two storey on a corner lot, dual street presentation, upper level living.",
    suburb: "Donnybrook",
    state: "VIC",
    postcode: "3064",
    status: "under-construction",
    bedrooms: 5,
    bathrooms: 3,
    carSpaces: 2,
    landSize: 604,
    houseSize: 302,
    placeholderVariant: "double-storey",
    completionLabel: "Completion window to be confirmed",
    priceDisplay: "Price on application",
    locationPrecision: "exact",
    latitude: -37.5008,
    longitude: 144.9601,
    isFeatured: false,
  },
  {
    id: "concept-dual-living",
    slug: "dual-living-concept",
    name: "Dual living concept",
    summary:
      "Two storey with a ground floor guest suite and separate second living area.",
    suburb: "Craigieburn",
    state: "VIC",
    postcode: "3064",
    status: "under-construction",
    bedrooms: 5,
    bathrooms: 3,
    carSpaces: 2,
    landSize: 578,
    houseSize: 288,
    placeholderVariant: "double-storey",
    completionLabel: "Completion window to be confirmed",
    locationPrecision: "approximate",
    latitude: -37.5906,
    longitude: 144.9487,
    isFeatured: false,
  },
  {
    id: "concept-rear-terrace",
    slug: "rear-terrace-concept",
    name: "Rear terrace concept",
    summary: "Townhouse plan with a north-facing rear terrace and study nook.",
    suburb: "Mickleham",
    state: "VIC",
    postcode: "3064",
    status: "sold",
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 1,
    landSize: 248,
    houseSize: 158,
    placeholderVariant: "townhouse",
    locationPrecision: "approximate",
    latitude: -37.5265,
    longitude: 144.8802,
    isFeatured: false,
  },
  {
    id: "concept-compact-single",
    slug: "compact-single-storey-concept",
    name: "Compact single storey concept",
    summary:
      "Three bedrooms on a compact lot, open plan living, single garage.",
    suburb: "Donnybrook",
    state: "VIC",
    postcode: "3064",
    status: "sold",
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 1,
    landSize: 294,
    houseSize: 152,
    placeholderVariant: "single-storey",
    locationPrecision: "private",
    latitude: -37.5124,
    longitude: 144.9498,
    isFeatured: false,
  },
  {
    id: "concept-garden-outlook",
    slug: "garden-outlook-concept",
    name: "Garden outlook concept",
    summary:
      "Single level with living opening to a landscaped garden, double garage.",
    suburb: "Craigieburn",
    state: "VIC",
    postcode: "3064",
    status: "completed",
    bedrooms: 4,
    bathrooms: 2,
    carSpaces: 2,
    landSize: 465,
    houseSize: 224,
    placeholderVariant: "single-storey",
    locationPrecision: "approximate",
    latitude: -37.6088,
    longitude: 144.9452,
    isFeatured: false,
  },
] as const;
